### ISSUE TITLE
Server certificate expired

### ISSUE THREAD

**Issue by matthijs678** [amatosg/restcountries#10]
When you visit the site, sometimes it shows a valid certificate, sometime it doesn't.

**Comment by amatosg** [comment]
You should clean your cache, please check https://www.sslshopper.com/ssl-checker.html#hostname=restcountries.com

**Comment by matthijs678** [comment]
The website can show the expired certificate. It seems to be random, because the first 2 checks did show the valid certificate.

![image](https://user-images.githubusercontent.com/75065558/162002545-29600eb1-580f-43ad-8136-53813ea5db22.png)

The certificate in my browser:
![image](https://user-images.githubusercontent.com/75065558/162003316-646ea116-8ab7-4444-9365-3ec84713967f.png)

**Comment by amatosg** [comment]
I've restarted the reverse proxy server, can you check again please?

**Comment by matthijs678** [comment]
Yes that works, thanks
