### ISSUE TITLE
What's happen to the API?

### ISSUE THREAD

**Issue by MoussaRiad** [amatosg/restcountries#13]
The API is not accessible due to server problem (error code 503), and it shows:
![503 Service Unavailable](https://user-images.githubusercontent.com/78734256/225935498-2cdeb932-f72e-41d1-b629-3b529c932754.png)

Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems.
Please try again later.
Apache/2.4.38 (Debian) Server at restcountries.com Port 443.
Is there any solution ?

**Comment by amatosg** [comment]
what is happening is that the server is running low on memory and it crashes, I upgraded the server and it shouldn't happen again (I hope...)

**Comment by jochy** [comment]
It sounds like it is still down :'(
